version: "3.3"

services:

  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    build:
      context: Backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/newBase?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: newBase
    restart: on-failure
    ports:
      - "8089:8089"
    networks:
      - mysql  
    depends_on:
      - mysql-db
    links:
      - mysql-db

  mysql-db:
    image: mysql:5.6
    platform: linux/amd64
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'newBase'
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
    networks:
      - mysql  

  front-end3:
    build:
      context: Frontend
      dockerfile: Dockerfile
    container_name: front-end3
    ports:
      - "3000:3000"
    command: react-scripts start
    links:
      - springboot-restful-webservices 
networks:
   mysql:
  